# Generated by Django 4.2.1 on 2023-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice", old_name="votes", new_name="points",
        ),
    ]
