# Generated by Django 4.2.1 on 2023-05-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_rename_votes_choice_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
